
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:22 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:22 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/ncs/toolchains/4f5b6ad6dd/"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/Scripts/"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/nanopb/generator-bin/"
      - "C:/ncs/toolchains/4f5b6ad6dd/nrfutil/bin/"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/zephyr-sdk/gnu/arm-zephyr-eabi/bin/"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/zephyr-sdk/gnu/riscv64-zephyr-elf/bin/"
      - "C:/Users/Bjorn/.vscode/extensions/nordic-semiconductor.nrf-connect-2026.9.2823-win32-x64/platform/nrfutil/lib/nrfutil-sdk-manager/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Users/Bjorn/.local/bin/"
      - "C:/Users/Bjorn/miniconda3/"
      - "C:/Users/Bjorn/miniconda3/Library/mingw-w64/bin/"
      - "C:/Users/Bjorn/miniconda3/Library/usr/bin/"
      - "C:/Users/Bjorn/miniconda3/Library/bin/"
      - "C:/Users/Bjorn/miniconda3/Scripts/"
      - "C:/Users/Bjorn/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Bjorn/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/Bjorn/AppData/Local/PowerToys/DSCModules/"
      - "C:/msys64/ucrt64/bin/"
    searched_directories:
      - "C:/ncs/toolchains/4f5b6ad6dd/ninja-build.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/ninja-build.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/ninja-build"
      - "C:/ncs/toolchains/4f5b6ad6dd/ninja.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/ninja.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/ninja"
      - "C:/ncs/toolchains/4f5b6ad6dd/samu.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/samu.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/samu"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/ninja-build.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/ninja-build.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/ninja-build"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/ninja.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/ninja.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/ninja"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/samu.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/samu.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/mingw64/bin/samu"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/ninja-build.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/ninja-build.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/ninja-build"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/ninja.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/ninja.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/ninja"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/samu.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/samu.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/bin/samu"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/ninja-build.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/ninja-build.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/ninja-build"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/ninja.com"
    found: "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/ninja.exe"
    search_context:
      ENV{PATH}:
        - "C:\\ncs\\toolchains\\4f5b6ad6dd"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\mingw64\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\bin\\Scripts"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\nanopb\\generator-bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\nrfutil\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\zephyr-sdk\\gnu\\arm-zephyr-eabi\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\zephyr-sdk\\gnu\\riscv64-zephyr-elf\\bin"
        - "c:\\Users\\Bjorn\\.vscode\\extensions\\nordic-semiconductor.nrf-connect-2026.9.2823-win32-x64\\platform\\nrfutil\\lib\\nrfutil-sdk-manager"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Users\\Bjorn\\.local\\bin"
        - "C:\\Users\\Bjorn\\miniconda3"
        - "C:\\Users\\Bjorn\\miniconda3\\Library\\mingw-w64\\bin"
        - "C:\\Users\\Bjorn\\miniconda3\\Library\\usr\\bin"
        - "C:\\Users\\Bjorn\\miniconda3\\Library\\bin"
        - "C:\\Users\\Bjorn\\miniconda3\\Scripts"
        - "C:\\Users\\Bjorn\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Bjorn\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Bjorn\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "C:\\msys64\\ucrt64\\bin"
  -
    kind: "find-v1"
    backtrace:
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/share/cmake-4.2/Modules/FindPython/Support.cmake:2437 (find_program)"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/share/cmake-4.2/Modules/FindPython3.cmake:671 (include)"
      - "C:/ncs/v3.4.1/zephyr/cmake/modules/python.cmake:41 (find_package)"
      - "C:/ncs/v3.4.1/zephyr/cmake/modules/user_cache.cmake:30 (include)"
      - "C:/ncs/v3.4.1/zephyr/cmake/modules/extensions.cmake:5 (include)"
      - "cmake/modules/sysbuild_default.cmake:8 (include)"
      - "C:/ncs/v3.4.1/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)"
      - "C:/ncs/v3.4.1/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "C:/ncs/v3.4.1/zephyr/share/sysbuild-package/cmake/SysbuildConfig.cmake:8 (include)"
      - "template/CMakeLists.txt:10 (find_package)"
    mode: "program"
    variable: "_Python3_EXECUTABLE_DEBUG"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "python3.12_d"
      - "python3_d"
      - "python_d"
    candidate_directories:
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/"
    searched_directories:
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python3.12_d.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python3.12_d.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python3.12_d"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python3_d.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python3_d.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python3_d"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python_d.com"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python_d.exe"
      - "C:/ncs/toolchains/4f5b6ad6dd/opt/bin/python_d"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\ncs\\toolchains\\4f5b6ad6dd"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\mingw64\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\bin\\Scripts"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\nanopb\\generator-bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\nrfutil\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\zephyr-sdk\\gnu\\arm-zephyr-eabi\\bin"
        - "C:\\ncs\\toolchains\\4f5b6ad6dd\\opt\\zephyr-sdk\\gnu\\riscv64-zephyr-elf\\bin"
        - "c:\\Users\\Bjorn\\.vscode\\extensions\\nordic-semiconductor.nrf-connect-2026.9.2823-win32-x64\\platform\\nrfutil\\lib\\nrfutil-sdk-manager"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Users\\Bjorn\\.local\\bin"
        - "C:\\Users\\Bjorn\\miniconda3"
        - "C:\\Users\\Bjorn\\miniconda3\\Library\\mingw-w64\\bin"
        - "C:\\Users\\Bjorn\\miniconda3\\Library\\usr\\bin"
        - "C:\\Users\\Bjorn\\miniconda3\\Library\\bin"
        - "C:\\Users\\Bjorn\\miniconda3\\Scripts"
        - "C:\\Users\\Bjorn\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Bjorn\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Bjorn\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "C:\\msys64\\ucrt64\\bin"
      CMAKE_INSTALL_PREFIX: "C:/Program Files (x86)/sysbuild_toplevel"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "C:/Program Files"
        - "C:/Program Files (x86)"
        - "C:/ncs/toolchains/4f5b6ad6dd/opt"
        - "C:/Program Files (x86)/sysbuild_toplevel"
...
