# Porten: PWM-baerebolge + ESB

CONFIG_PWM=y

CONFIG_ESB=y
CONFIG_CLOCK_CONTROL=y
CONFIG_ESB_CLOCK_INIT=y

# 32768 tikk per sekund gir 30,5 us opplosning pa portens klokke.
# Standardverdien kan vaere 1000, altsa 1 ms - for grovt for oss.
CONFIG_SYS_CLOCK_TICKS_PER_SEC=32768
